resolver: lts-14.27
packages:
- .
extra-deps:
- git: https://gitlab.imn.htwk-leipzig.de/waldmann/cyp
  commit: 234a22bff0437e9e357a251125fcfb39da83b5ee
- haskell-src-exts-simple-1.21.1.0
- algebraic-graphs-0.5